services:
  - type: web
    name: contest-frontend
    env: static
    staticPublishPath: /public
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
